### ISSUE TITLE
English dataset

### ISSUE THREAD

**Issue by lisaterumi** [nerel-ds/NEREL-BIO#1]
Hello, I am interested in nested named entities and I would like to know if the English dataset is available (100+ English abstracts).
 
Regards

**Comment by tutubalinaev** [comment]
Dear @lisaterumi,

we are going to publish the English part a little bit later. Hopefully, we will organize a shared task on nested NER in the biomedical domain.

Best regards,
Elena

**Comment by lisaterumi** [comment]
Ok, thanks for the feedback.

Regards

**Comment by tutubalinaev** [comment]
Dear @lisaterumi, 
As part of the CLEF 2024 conference, we are running a competition on Nested Named Entities Recognition in the biomedical domain. The competition is held on English and Russian scientific abstracts in medical field.

You can join the competition and get the data set via the registration link: http://participants-area.bioasq.org/

Details of the task and registration are available at the competition page: https://github.com/nerel-ds/NEREL-BIO/tree/master/bio-nne
