### ISSUE TITLE
RuntimeError: shape '[16, 128]' is invalid for input of size 8192

### ISSUE THREAD

**Issue by hasin-ruet13** [nerel-ds/NEREL-BIO#4]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File ~/BioASQ/NEREL-BIO-master/bio-nne/baseline_model/run_ner.py:745
    741     main()
    744 if __name__ == "__main__":
--> 745     main()

File ~/BioASQ/NEREL-BIO-master/bio-nne/baseline_model/run_ner.py:686, in main()
    684     checkpoint = last_checkpoint
    685 # with profiler_callback.profiler:
--> 686 train_result = trainer.train(resume_from_checkpoint=checkpoint)
    687 trainer.save_model()  # Saves the tokenizer too for easy upload
    689 metrics = train_result.metrics

File ~/.conda/envs/my_env/lib/python3.9/site-packages/transformers/trainer.py:1553, in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1551         hf_hub_utils.enable_progress_bars()
   1552 else:
-> 1553     return inner_training_loop(
   1554         args=args,
   1555         resume_from_checkpoint=resume_from_checkpoint,
   1556         trial=trial,
   1557         ignore_keys_for_eval=ignore_keys_for_eval,
   1558     )

File ~/.conda/envs/my_env/lib/python3.9/site-packages/transformers/trainer.py:1835, in Trainer._inner_training_loop(self, batch_size, args, resume_from_checkpoint, trial, ignore_keys_for_eval)
   1832     self.control = self.callback_handler.on_step_begin(args, self.state, self.control)
   1834 with self.accelerator.accumulate(model):
-> 1835     tr_loss_step = self.training_step(model, inputs)
   1837 if (
   1838     args.logging_nan_inf_filter
   1839     and not is_torch_tpu_available()
   1840     and (torch.isnan(tr_loss_step) or torch.isinf(tr_loss_step))
   1841 ):
   1842     # if loss is nan or inf simply add the average of previous logged losses
   1843     tr_loss += tr_loss / (1 + self.state.global_step - self._globalstep_last_logged)

File ~/.conda/envs/my_env/lib/python3.9/site-packages/transformers/trainer.py:2679, in Trainer.training_step(self, model, inputs)
   2676     return loss_mb.reduce_mean().detach().to(self.args.device)
   2678 with self.compute_loss_context_manager():
-> 2679     loss = self.compute_loss(model, inputs)
   2681 if self.args.n_gpu > 1:
   2682     loss = loss.mean()  # mean() to average on multi-gpu parallel training

File ~/.conda/envs/my_env/lib/python3.9/site-packages/transformers/trainer.py:2704, in Trainer.compute_loss(self, model, inputs, return_outputs)
   2702 else:
   2703     labels = None
-> 2704 outputs = model(**inputs)
   2705 # Save past state if it exists
   2706 # TODO: this needs to be fixed and made cleaner later.
   2707 if self.args.past_index >= 0:

File ~/.conda/envs/my_env/lib/python3.9/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~/.conda/envs/my_env/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py:171, in DataParallel.forward(self, *inputs, **kwargs)
    169     return self.module(*inputs[0], **kwargs[0])
    170 replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
--> 171 outputs = self.parallel_apply(replicas, inputs, kwargs)
    172 return self.gather(outputs, self.output_device)

File ~/.conda/envs/my_env/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py:181, in DataParallel.parallel_apply(self, replicas, inputs, kwargs)
    180 def parallel_apply(self, replicas, inputs, kwargs):
--> 181     return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])

File ~/.conda/envs/my_env/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py:89, in parallel_apply(modules, inputs, kwargs_tup, devices)
     87     output = results[i]
     88     if isinstance(output, ExceptionWrapper):
---> 89         output.reraise()
     90     outputs.append(output)
     91 return outputs

File ~/.conda/envs/my_env/lib/python3.9/site-packages/torch/_utils.py:644, in ExceptionWrapper.reraise(self)
    640 except TypeError:
    641     # If the exception takes multiple arguments, don't try to
    642     # instantiate since we don't know how to
    643     raise RuntimeError(msg) from None
--> 644 raise exception

RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/hasin.rehana/.conda/envs/my_env/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/home/hasin.rehana/.conda/envs/my_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hasin.rehana/BioASQ/NEREL-BIO-master/bio-nne/baseline_model/src/model.py", line 239, in forward
    start_negative_mask = ner["start_negative_mask"].reshape(batch_size * num_types, seq_length)
RuntimeError: shape '[16, 128]' is invalid for input of size 8192

**Comment by tutubalinaev** [comment]
This is error in the BINDER code, please see https://github.com/microsoft/binder
